sylius_resource:
    resources:
        odiseo_blog.article:
            driver: doctrine/orm
            classes:
                model: Odiseo\SyliusBlogPlugin\Entity\Article
                interface: Odiseo\SyliusBlogPlugin\Entity\ArticleInterface
                repository: Odiseo\SyliusBlogPlugin\Repository\ArticleRepository
                form: Odiseo\BlogBundle\Form\Type\ArticleType

        odiseo_blog.article_comment:
            driver: doctrine/orm
            classes:
                model: Odiseo\SyliusBlogPlugin\Entity\ArticleComment
                repository: Odiseo\SyliusBlogPlugin\Repository\ArticleCommentRepository
                form: Odiseo\BlogBundle\Form\Type\ArticleCommentType

        odiseo_blog.article_category:
            driver: doctrine/orm
            classes:
                model: Odiseo\BlogBundle\Model\ArticleCategory
                repository: Odiseo\BlogBundle\Doctrine\ORM\ArticleCategoryRepository
                form: Odiseo\BlogBundle\Form\Type\ArticleCategoryType
